import type { Booking, Listing, Notification, Review, Thread, UserProfile } from "./types";

export const demoUsers: UserProfile[] = [
  {
    id: "user-rhea",
    name: "Rhea Malhotra",
    email: "rhea@rentify.test",
    city: "Bangalore",
    bio: "Weekend creator, careful renter, and camera gear obsessive.",
    avatar: "RM",
    rating: 4.9,
    reviewCount: 42,
    verified: true,
    role: "renter",
    listedItems: 2,
    rentalHistory: 18,
  },
  {
    id: "user-arjun",
    name: "Arjun Kapur",
    email: "arjun@rentify.test",
    city: "Bangalore",
    bio: "Photography studio owner. I rent clean, tested equipment with flexible pickup.",
    avatar: "AK",
    rating: 5,
    reviewCount: 128,
    verified: true,
    role: "owner",
    listedItems: 7,
    rentalHistory: 96,
  },
  {
    id: "user-priya",
    name: "Priya Shah",
    email: "priya@rentify.test",
    city: "Bangalore",
    bio: "Designer wardrobe curator with event-ready outfits and jewelry.",
    avatar: "PS",
    rating: 4.8,
    reviewCount: 76,
    verified: true,
    role: "owner",
    listedItems: 14,
    rentalHistory: 121,
  },
  {
    id: "user-admin",
    name: "Rentify Admin",
    email: "admin@rentify.test",
    city: "Bangalore",
    bio: "Marketplace operations and trust team.",
    avatar: "RA",
    rating: 5,
    reviewCount: 12,
    verified: true,
    role: "admin",
    listedItems: 0,
    rentalHistory: 0,
  },
];

export const categories = [
  "All",
  "Cameras",
  "Vehicles",
  "Fashion",
  "Tools",
  "Gaming",
  "Music",
  "Outdoors",
  "Electronics",
  "Events",
  "Appliances",
];

export const demoListings: Listing[] = [
  {
    id: "lst-camera-a7",
    ownerId: "user-arjun",
    ownerName: "Arjun Kapur",
    ownerAvatar: "AK",
    ownerRating: 5,
    title: "Sony Alpha A7 IV Full Frame Camera Kit",
    description: "Body, 24-70mm f/2.8 lens, batteries, charger, SD cards, and a weatherproof case. Ideal for weddings, shoots, and travel.",
    category: "Cameras",
    city: "Bangalore",
    area: "Koramangala",
    pricePerDay: 800,
    securityDeposit: 6000,
    delivery: "both",
    availability: "available",
    availableFrom: "2026-06-03",
    availableTo: "2026-08-30",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=1200&q=80",
    ],
    rating: 4.9,
    reviewCount: 128,
    badge: "Featured",
    featured: true,
    createdAt: "2026-05-28T10:00:00.000Z",
    reports: 0,
  },
  {
    id: "lst-car-swift",
    ownerId: "user-arjun",
    ownerName: "Arjun Kapur",
    ownerAvatar: "AK",
    ownerRating: 4.8,
    title: "Maruti Swift Dzire Self Drive",
    description: "Clean automatic sedan with phone mount, fast charger, and city pickup. Owner reviews renters before approval.",
    category: "Vehicles",
    city: "Bangalore",
    area: "Indiranagar",
    pricePerDay: 1200,
    securityDeposit: 8000,
    delivery: "pickup",
    availability: "limited",
    availableFrom: "2026-06-05",
    availableTo: "2026-07-20",
    images: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.8,
    reviewCount: 64,
    badge: "Hot",
    createdAt: "2026-05-24T10:00:00.000Z",
    reports: 1,
  },
  {
    id: "lst-lehenga",
    ownerId: "user-priya",
    ownerName: "Priya Shah",
    ownerAvatar: "PS",
    ownerRating: 4.9,
    title: "Designer Wedding Lehenga",
    description: "Deep rose handwork lehenga with blouse and dupatta. Dry cleaned after every rental, fitting consultation included.",
    category: "Fashion",
    city: "Bangalore",
    area: "HSR Layout",
    pricePerDay: 2500,
    securityDeposit: 10000,
    delivery: "delivery",
    availability: "available",
    availableFrom: "2026-06-02",
    availableTo: "2026-09-10",
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.9,
    reviewCount: 32,
    badge: "New",
    createdAt: "2026-05-31T09:00:00.000Z",
    reports: 0,
  },
  {
    id: "lst-partybox",
    ownerId: "user-rhea",
    ownerName: "Rhea Malhotra",
    ownerAvatar: "RM",
    ownerRating: 4.9,
    title: "JBL PartyBox 300 Speaker",
    description: "Battery speaker with mic input, light effects, and aux cables. Great for house parties and small events.",
    category: "Music",
    city: "Bangalore",
    area: "BTM Layout",
    pricePerDay: 600,
    securityDeposit: 3000,
    delivery: "both",
    availability: "available",
    availableFrom: "2026-06-01",
    availableTo: "2026-08-01",
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80"],
    rating: 5,
    reviewCount: 89,
    badge: "Top rated",
    createdAt: "2026-05-22T09:00:00.000Z",
    reports: 0,
  },
  {
    id: "lst-camping",
    ownerId: "user-rhea",
    ownerName: "Rhea Malhotra",
    ownerAvatar: "RM",
    ownerRating: 4.7,
    title: "Six Person Camping Tent Kit",
    description: "Tent, ground sheet, two lanterns, sleeping mats, and a compact stove. Sanitized and packed after every trip.",
    category: "Outdoors",
    city: "Bangalore",
    area: "Whitefield",
    pricePerDay: 400,
    securityDeposit: 2500,
    delivery: "pickup",
    availability: "available",
    availableFrom: "2026-06-04",
    availableTo: "2026-09-01",
    images: ["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.7,
    reviewCount: 41,
    badge: "Popular",
    createdAt: "2026-05-18T09:00:00.000Z",
    reports: 0,
  },
  {
    id: "lst-drill",
    ownerId: "user-arjun",
    ownerName: "Arjun Kapur",
    ownerAvatar: "AK",
    ownerRating: 4.6,
    title: "Bosch Drill and Full Tool Kit",
    description: "Hammer drill, screwdriver bits, measuring tape, level, anchors, and safety glasses for quick home projects.",
    category: "Tools",
    city: "Bangalore",
    area: "Marathahalli",
    pricePerDay: 250,
    securityDeposit: 1500,
    delivery: "both",
    availability: "available",
    availableFrom: "2026-06-01",
    availableTo: "2026-10-01",
    images: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.6,
    reviewCount: 77,
    badge: "Hot",
    createdAt: "2026-05-14T09:00:00.000Z",
    reports: 0,
  },
  {
    id: "lst-ps5",
    ownerId: "user-priya",
    ownerName: "Priya Shah",
    ownerAvatar: "PS",
    ownerRating: 4.9,
    title: "PS5 Console with Five Games",
    description: "Console, two controllers, FIFA, Spider-Man, Gran Turismo, and charging dock. Same-day pickup available.",
    category: "Gaming",
    city: "Bangalore",
    area: "Jayanagar",
    pricePerDay: 700,
    securityDeposit: 5000,
    delivery: "pickup",
    availability: "limited",
    availableFrom: "2026-06-08",
    availableTo: "2026-07-31",
    images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.9,
    reviewCount: 23,
    badge: "New",
    createdAt: "2026-05-30T09:00:00.000Z",
    reports: 0,
  },
  {
    id: "lst-macbook",
    ownerId: "user-arjun",
    ownerName: "Arjun Kapur",
    ownerAvatar: "AK",
    ownerRating: 4.7,
    title: "MacBook Pro M3 16 inch",
    description: "M3 Pro, 36GB RAM, Final Cut, Logic, Adobe apps, charger, and protective sleeve for edit suites and shoots.",
    category: "Electronics",
    city: "Bangalore",
    area: "Electronic City",
    pricePerDay: 1500,
    securityDeposit: 15000,
    delivery: "both",
    availability: "available",
    availableFrom: "2026-06-01",
    availableTo: "2026-08-15",
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.7,
    reviewCount: 38,
    badge: "Hot",
    createdAt: "2026-05-27T09:00:00.000Z",
    reports: 0,
  },
];

export const demoBookings: Booking[] = [
  {
    id: "book-001",
    listingId: "lst-partybox",
    renterId: "user-arjun",
    ownerId: "user-rhea",
    startDate: "2026-06-06",
    endDate: "2026-06-08",
    status: "pending",
    note: "Need it for a terrace birthday party. Pickup works for me.",
    createdAt: "2026-06-01T08:00:00.000Z",
  },
  {
    id: "book-002",
    listingId: "lst-camera-a7",
    renterId: "user-rhea",
    ownerId: "user-arjun",
    startDate: "2026-06-11",
    endDate: "2026-06-13",
    status: "accepted",
    note: "Short film shoot. Can collect from Koramangala.",
    createdAt: "2026-05-31T08:00:00.000Z",
  },
];

export const demoThreads: Thread[] = [
  {
    id: "thread-camera-rhea",
    listingId: "lst-camera-a7",
    renterId: "user-rhea",
    ownerId: "user-arjun",
    messages: [
      {
        id: "msg-1",
        senderId: "user-rhea",
        body: "Is the 24-70 lens included for June 11?",
        createdAt: "2026-06-01T08:14:00.000Z",
      },
      {
        id: "msg-2",
        senderId: "user-arjun",
        body: "Yes, lens, two batteries, charger, and SD cards are included.",
        createdAt: "2026-06-01T08:16:00.000Z",
      },
    ],
  },
];

export const demoReviews: Review[] = [
  {
    id: "rev-001",
    listingId: "lst-camera-a7",
    fromUserId: "user-rhea",
    toUserId: "user-arjun",
    rating: 5,
    body: "Camera was spotless and Arjun explained every setting I needed.",
    createdAt: "2026-05-20T08:00:00.000Z",
  },
  {
    id: "rev-002",
    listingId: "lst-lehenga",
    fromUserId: "user-rhea",
    toUserId: "user-priya",
    rating: 5,
    body: "Beautiful outfit, clear sizing help, and very easy delivery.",
    createdAt: "2026-05-25T08:00:00.000Z",
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "not-001",
    title: "New booking request",
    body: "Arjun requested your JBL PartyBox for June 6 to June 8.",
    type: "booking",
    read: false,
    createdAt: "2026-06-01T08:00:00.000Z",
  },
  {
    id: "not-002",
    title: "Message received",
    body: "Arjun replied about the camera kit.",
    type: "message",
    read: false,
    createdAt: "2026-06-01T08:16:00.000Z",
  },
];
